tasks:
  - name: Install geth
    init: |
      sudo apt update
      sudo apt install -y software-properties-common
      sudo add-apt-repository -y ppa:ethereum/ethereum
      sudo apt update
      sudo apt install -y geth
